default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: portal_test
  password: portal_test
  host: localhost

development:
  <<: *default
  database: portal_test_gest

test:
  <<: *default
  database: trading_app_test

production:
  <<: *default
  database: trading_app_production
  username: trading_app
  password: <%= ENV['TRADING_APP_DATABASE_PASSWORD'] %>

